before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: cloudsql
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
metadata:
notarize:
gomod:
github_urls:
release:
snapcrafts:
  -
dist:
source:
project_name:
kos:
  -
signs:
  -
git:
scoops:
  -
aurs:
  -
report_sizes: false
publishers:
  -
nix:
  -
nfpms:
  -
blobs:
  -
universal_binaries:
  -
krews:
  -
sboms:
  -
chocolateys:
  -
gitlab_urls:
artifactories:
  -
gitea_urls:
force_token: github
env:
  -
version: 2
dockers:
  -
env_files:
announce:
uploads:
  -
winget:
  -
docker_manifests:
  -
milestones:
  -
upx:
  -
brews:
  - name: homebrew-cloudsql
    repository:
      owner: s-okayama
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/s-okayama/cloudsql
    description: cloudsql
    test: |
      system "#{bin}/cloudsql --version"